### ISSUE TITLE
How to get system space usage via PureStoragePowerShellSDK2

### ISSUE THREAD

**Issue by hugh-martin** [PureStorage-Connect/PowerShellSDK2#1]
It seems as if the PureStoragePowerShellSDK (v1) module is not compatible with PowerShell 7, so I need to move to the PureStoragePowerShellSDK2 module.  Our arrays support it, so we're good there.  With the v1 module, I am using the Get-PfaArraySpaceMetrics cmdlet to get some data from our arrays.  How can I get this information when using the PureStoragePowerShellSDK2 module with PowerShell 7?

**Comment by mikenelson-io** [comment]
The FA SDK v1 requires .Net Framework, so it is not compatible with .net Core, as the documentation states.
PowerShell 5.1 is installed by default on every Windows 10/Server OS, so SDK v1 will run unless you have a requirement for PoSH v7.x, such as possibly you are running on Linux or Mac. The next release of 1.x should have .net Core compatibility. Also, as mentioned in the documentation and videos, you can run SDK v1 and SDK v2 together in a PowerShell 5.1 session.

Get-Pfa2ArraySpace will provide you with some metrics. SDKv2 does not yet have full API parity with Purity so it may not have all of the data exposure that SDK v1 has. If that specific data is still required, until the next releases are available, we would suggest 1) continuing to use SDK v1 in PoSH 5.1, or 2) use another SDK such as Python to gather your required data.

**Comment by hugh-martin** [comment]
Got it.  Thanks.
