### ISSUE TITLE
The 2.2.279 tagged release is actually labeled as 2.2.276 when installed

### ISSUE THREAD

**Issue by lukeroberts** [PureStorage-Connect/PowerShellSDK2#12]
Does the tag need to be updated or does the version within the msi/powershell gallery need to be updated to 2.2.279?:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1096744/173090632-7395dd4a-23b1-4e97-b5aa-db387da86c5c.png">

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1096744/173108375-259822e5-6047-4661-9f09-e1a5f3ec517d.png">

**Comment by rquimbey** [comment]
yes the tag needs to be updated. This is 100% my fatfinger fault. It is now 2.2.276 as it should be in the tag.

**Comment by rquimbey** [comment]
it is correct now, and its also correct in the psgallery: https://www.powershellgallery.com/packages/PureStoragePowerShellSDK2/2.2.276.0

thank you Luke!

**Comment by rquimbey** [comment]
fixed!

**Comment by lukeroberts** [comment]
> fixed!

Thanks!
