### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by flipflopdad** [PureStorage-Connect/PowerShellSDK2#14]
URL: https://github.com/PureStorage-Connect/PowerShellSDK2/blob/master/SDK2-Examples.ps1

Line 53 has a parameter called "Credentials"... that throws an error

Changing it to "Credential" allowed me to connect.

Thanks!

**Comment by barkz** [comment]
Fixed

**Comment by barkz** [comment]
Fixed
