### ISSUE TITLE
PureStoragePowerShellSDK2 cmdlets return blank lines when running within an IDE

### ISSUE THREAD

**Issue by hugh-martin** [PureStorage-Connect/PowerShellSDK2#2]
When using the PureStoragePowerShellSDK2 module from within an IDE, such as VS Code, Sapien PowerShell Studio, ISE, etc., some (or all) cmdlets from the PureStoragePowerShellSDK2 module return only blank lines.  For example, all of these will return blank lines:

```
Get-Pfa2Volume

$vols = Get-Pfa2Volume #no output expected here
$vols
$vols | Select-Object Name
$vols | Get-Member
Write-Output $vols
```

These commands, however, will return data:

```
$count = ($vols | Measure-Object).Count #no output expected here
$count

$volnames = $vols.Name #no output expected here
$volnames

foreach ($vol in $vols) {
    $volname = $vol.Name
    Write-Output $volname
}
```

This issue was confirmed by Pure support.  See case #00934363.

**Comment by mikenelson-io** [comment]
I don't believe we can classify this as a bug since it does not hamper the cmdlet execution. Are you asking that this extra line be removed?

**Comment by mikenelson-io** [comment]
I remember some internal discussion around this issue. And I do know a bug has been filed. Although, we have not been able to reproduce the issue every time with different IDEs and/or different versions of PowerShell. As an example, when I run these commands in the VSCode Insiders build with PoSH 7.1.3 terminal, it returns output for me. When run inside the PoSH 5.1 IDE, it does not return output.

**Comment by hugh-martin** [comment]
Understood.  It happens for me 100% of the time with Sapien PowerShell Studio 2020 and 2021, as well as ISE on Windows 10 1909.
