### ISSUE TITLE
Get-Pfa2Array doesn't contain replication value, but API does.

### ISSUE THREAD

**Issue by saidbrandon** [PureStorage-Connect/PowerShellSDK2#6]
Get-Pfa2Array
```csharp
class Space {
   DataReduction: 
   Shared: 
   Snapshots: 
   System: 
   ThinProvisioning: 
   TotalPhysical: 
   TotalProvisioned: 
   TotalReduction: 
   Unique: 
   Virtual: 
}
```
JSON Response via -Verbose
```json
"space":{
	"data_reduction":
	"shared":,
	"snapshots":,
	"system":,
	"thin_provisioning":,
	"total_physical":,
	"total_provisioned":,
	"total_reduction":,
	"unique":,
	"virtual":,
	"replication":
}
```

**Comment by barkz** [comment]
@saidbrandon This has been resolved in SDK 2.16.12.0. Example from my FlashArray running 6.4.1.

**Without Verbose**
`PS C:\Users\barkz> Get-Pfa2Array


Id                 : 723ec7b5-b427-453e-a3cf-9584bab9483d
Name               : sn1-x70r2-f03-30
Banner             : barkz@purestorage.com
Capacity           : 272353502167040
ConsoleLockEnabled : False
Encryption         : @{DataAtRest=@{Algorithm='AES-256-CTR'; Enabled=True}; ModuleVersion='FA-1.3'}
EradicationConfig  : @{EradicationDelay=86400000; ManualEradication='all-disabled'}
IdleTimeout        : 0
NtpServers         : {time.soln.local}
Os                 : Purity//FA
Parity             : 1
ScsiTimeout        : 60000
Space              : @{DataReduction=1; Shared=458924868117; Snapshots=228853107790; System=0; ThinProvisioning=1; 
                     TotalPhysical=687777975907; TotalProvisioned=1073741824; TotalReduction=1; Unique=0; Virtual=0; Replication=0; 
                     SharedEffective=7810934784; SnapshotsEffective=774440149504; TotalEffective=782251084288; UniqueEffective=0}
Version            : 6.4.1`

**Comment by barkz** [comment]
**With Verbose**

PS C:\Users\barkz> Get-Pfa2Array -Verbose
VERBOSE: PureStorage.Rest Verbose: 13 : 2023-05-05T20:56:48.9573904Z 10.21.219.60: Get-Pfa2Array (__AllParameterSets) Verbose=True

VERBOSE: PureStorage.Rest Verbose: 10 : 2023-05-05T20:56:48.9834226Z GET https://10.21.219.60/api/2.20/arrays <no body>

VERBOSE: PureStorage.Rest Verbose: 11 : 2023-05-05T20:56:49.0210991Z GET https://10.21.219.60/api/2.20/arrays 200 38ms {"continuation_tok
en":null,"items":[{"name":"sn1-x70r2-f03-30","id":"723ec7b5-b427-453e-a3cf-9584bab9483d","space":{"data_reduction":1.0,"shared":458924868
117,"snapshots":228853107790,"system":0,"thin_provisioning":1.0,"total_physical":687777975907,"total_provisioned":1073741824,"total_reduc
tion":1.0,"unique":0,"virtual":0,"unique_effective":0,"snapshots_effective":774440149504,"total_effective":782251084288,"replication":0,"
shared_effective":7810934784},"capacity":272353502167040,"parity":1.0,"eradication_config":{"manual_eradication":"all-disabled","eradicat
ion_delay":86400000},"console_lock_enabled":false,"encryption":{"data_at_rest":{"algorithm":"AES-256-CTR","enabled":true},"module_version
":"FA-1.3"},"idle_timeout":0,"ntp_servers":["time.soln.local"],"os":"Purity//FA","scsi_timeout":60000,"version":"6.4.1","banner":"barkz@p
urestorage.com"}],"more_items_remaining":false,"total_item_count":null}

Id                 : 723ec7b5-b427-453e-a3cf-9584bab9483d
Name               : sn1-x70r2-f03-30
Banner             : barkz@purestorage.com
Capacity           : 272353502167040
ConsoleLockEnabled : False
Encryption         : @{DataAtRest=@{Algorithm='AES-256-CTR'; Enabled=True}; ModuleVersion='FA-1.3'}
EradicationConfig  : @{EradicationDelay=86400000; ManualEradication='all-disabled'}
IdleTimeout        : 0
NtpServers         : {time.soln.local}
Os                 : Purity//FA
Parity             : 1
ScsiTimeout        : 60000
Space              : @{DataReduction=1; Shared=458924868117; Snapshots=228853107790; System=0; ThinProvisioning=1; 
                     TotalPhysical=687777975907; TotalProvisioned=1073741824; TotalReduction=1; Unique=0; Virtual=0; Replication=0; 
                     SharedEffective=7810934784; SnapshotsEffective=774440149504; TotalEffective=782251084288; UniqueEffective=0}
Version            : 6.4.1

**Comment by barkz** [comment]
@saidbrandon not sure what SDK version you are on. Let me know that detail.
